# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='', max_length=32, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=32, verbose_name='真实姓名'),
        ),
    ]
