# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190503_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nick',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=124, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=32, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, verbose_name='学号'),
        ),
    ]
