# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190503_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nick',
        ),
    ]
