# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(default='', max_length=30, primary_key=True, serialize=False, verbose_name='活动ID')),
                ('manager', models.CharField(default='', max_length=12, verbose_name='活动负责人')),
                ('relation_qq', models.CharField(default='', max_length=13, verbose_name='联系方式')),
                ('adress_act', models.CharField(default='', max_length=80, verbose_name='活动地点')),
                ('theme', models.CharField(default='', max_length=50, verbose_name='主题')),
                ('content', models.TextField(default='', verbose_name='活动内容')),
                ('time_begin', models.DateTimeField(default=django.utils.timezone.now, max_length=12, verbose_name='发起活动时间')),
                ('time_end', models.DateTimeField(default=django.utils.timezone.now, max_length=12, verbose_name='结束活动时间')),
                ('num_min', models.IntegerField(default='', verbose_name='最少参加人数')),
                ('num_max', models.IntegerField(default='', verbose_name='最多参加人数')),
                ('cost', models.CharField(choices=[('pay', '产生费用'), ('free', '免费')], default='free', max_length=50)),
                ('position', models.TextField(default='', verbose_name='职位安排')),
                ('intergral_add', models.IntegerField(default='', verbose_name='所得积分')),
                ('credit_add', models.IntegerField(default='', verbose_name='所得信用分')),
                ('user', models.ManyToManyField(default='', related_name='_activity_user_+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '活动表',
                'verbose_name_plural': '活动表',
            },
        ),
        migrations.CreateModel(
            name='ActivityPart',
            fields=[
                ('activity_part_id', models.AutoField(default='', primary_key=True, serialize=False, verbose_name='活动参与表ID')),
                ('participant', models.CharField(default='', max_length=12, verbose_name='参与人')),
                ('activity_ing', models.CharField(default='', max_length=30, verbose_name='正在参加的活动')),
                ('activity_will', models.CharField(default='', max_length=100, verbose_name='将要参加的活动')),
                ('activity_end', models.TextField(blank=True, default='', verbose_name='参加过的活动')),
                ('now_integer', models.IntegerField(default='', verbose_name='积分')),
                ('now_credit', models.IntegerField(default='', verbose_name='信用分')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.Activity')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活动参与表',
                'verbose_name_plural': '活动参与表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(default='', max_length=30, primary_key=True, serialize=False, verbose_name='评论表ID')),
                ('participant', models.CharField(default='', max_length=12, verbose_name='参与人')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评价')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.Activity')),
                ('activity_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.ActivityPart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
            },
        ),
    ]
