# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False, verbose_name='活动ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='credit_add',
            field=models.IntegerField(default=1, verbose_name='所得信用分'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='intergral_add',
            field=models.IntegerField(default=3, verbose_name='所得积分'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='num_max',
            field=models.IntegerField(default=8, verbose_name='最多参加人数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='num_min',
            field=models.IntegerField(default=1, verbose_name='最少参加人数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(related_name='_activity_user_+', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
