# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeapp', '0002_auto_20181228_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypart',
            name='activity_part_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='活动参与表ID'),
        ),
        migrations.AlterField(
            model_name='activitypart',
            name='now_credit',
            field=models.IntegerField(default=1, verbose_name='信用分'),
        ),
        migrations.AlterField(
            model_name='activitypart',
            name='now_integer',
            field=models.IntegerField(default=3, verbose_name='积分'),
        ),
    ]
