# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeapp', '0003_auto_20181228_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False, verbose_name='评论表ID'),
        ),
    ]
