# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge_books',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False, verbose_name='挑战书ID')),
                ('challenge_theme', models.CharField(default='', max_length=50, verbose_name='主题')),
                ('challenge_brief', models.TextField(blank=True, default='', verbose_name='简介')),
                ('challenge_rule', models.TextField(blank=True, default='', verbose_name='规则')),
                ('challenge_status', models.CharField(choices=[('cha_ing', '正在挑战'), ('cha_end', '挑战结束')], default='cha_ing', max_length=6)),
                ('challenge_time', models.CharField(default='', max_length=100, verbose_name='时间段')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '挑战书表',
                'verbose_name_plural': '挑战书表',
            },
        ),
    ]
