# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_books',
            name='challenge_status',
            field=models.CharField(choices=[('cha_ing', '正在挑战'), ('cha_end', '挑战结束')], default='cha_ing', max_length=25),
        ),
    ]
